version: "3.8"
services:
  db-backup:
    build: .
    environment:
    # env
      - DEBUG_MODE=true
    # file
      - FILE_NAME=
    # db
      - DB_ENGINE=
      - DB_HOST=
      - DB_PORT=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_NAME=
    # aws
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - S3_BUCKET_NAME=
    volumes:
      - ./app/:/app/
    restart: always