version: "3.8"
services:
  db-backup:
    build: .
    environment:
      - FILE_NAME=mybackup
      - DB_ENGINE=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=pass
      - DB_NAME=mydb
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=us-west-1
      - S3_BUCKET_NAME=mybucket
    volumes:
      - ./app/:/app/
    restart: always