apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup-myapp
spec:
  # run at midnight pst
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: db-backup
              image: kristianwindsor/db-backup
              env:
                - name: ACTION
                  value: "backup"
                - name: DEBUG_MODE
                  value: "false"
              envFrom:
                - configMapRef:
                    name: db-backup-myapp
                - secretRef:
                    name: db-backup-myapp
          restartPolicy: OnFailure