name: Build and Push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # git checkout
      - name: Checkout
        uses: actions/checkout@v2
      # buildx
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # dockerhub auth
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: kristianwindsor
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # build and push docker image
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kristianwindsor/db-backup:latest,kristianwindsor/db-backup:b${{ github.run_number }}